export const skillsData=[{
    label:"FRONT END",
    data:[{
        skillName:"HTML",
        percentage:"90"
    },{
        skillName:"CSS",
        percentage:"90"
    },{
        skillName:"JAVASCRIPT",
        percentage:"85"
    },{
        skillName:"REACT",
        percentage:"95"
    },{
        skillName:"REDUX",
        percentage:"70"
    },{
        skillName:"AJAX",
        percentage:"75"
    },{
        skillName:"FIGMA",
        percentage:"100"
    }],
},{
    label:"BACK END",
    data:[{
        skillName:"NODEJS",
        percentage:"85"
    },{
        skillName:"EXPRESSJS",
        percentage:"80"
    }]
},{
    label:"DATABASES",
    data:[{
        skillName:"MONGODB",
        percentage:"90"
    },{
        skillName:"MYSQL",
        percentage:"80"
    }]
}]